/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aliyun_ushell_OpenCVHelper */

#ifndef _Included_com_aliyun_ushell_OpenCVHelper
#define _Included_com_aliyun_ushell_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aliyun_ushell_OpenCVHelper
 * Method:    compareImages
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_aliyun_ushell_OpenCVHelper_compareImages
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
